source: /home/user/ec2-user/io/ofsaleem.github.io/
timezone: America/New_York

defaults:
        -
                scope:
                        path: ""
                        type: "posts"
                values:
                layout: "default"

